version: '2'
services:
  db:
    image: mysql
    #volumes:
      #- "./.data/db:/var/lib/mysql"
    restart: always
    #ports:
      #- "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mms
      MYSQL_USER: root
      MYSQL_PASSWORD: root
 
  web:
    image: mms
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    links:
      - db
    #extra_hosts:
    #- "db:10.94.42.35"
    environment:
      APP_DB_PASSWORD: root
      APP_DB_USER: root
      APP_DB_NAME: mms
      APP_DB_HOST: db
      APP_DB_DRIVER: "com.mysql.jdbc.Driver"
      APP_DB_DIALECT: "org.hibernate.dialect.MySQL5InnoDBDialect"
      APP_DB_URI: "jdbc:mysql://db:3306/mms"
