---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
dataSource:
     pooled: true
     jmxExport: true
     driverClassName: com.mysql.jdbc.Driver     
     username: root
     password: ThisIsNotAnExit      
environments:
    development:
        server:
            'contextPath': '/mms'
            session-timeout: 3600 # session timeout in seconds 
        dataSource:
            ##### set to create-drop to get a clean bootstrapped environment ####
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            #url: jdbc:mysql://db:3306/mms?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
        CacheLocation: C:/MMS-cache/
        MDSXMLFolder: C:/MMS-cache/mdsxmls/
        PlannerXMLFolder: C:/MMS-cache/plannerxmls/
        AlchemyXMLFolder: C:/MMS-cache/alchemyxmls/
        MappingXMLFolder: C:/MMS-cache/MappingXml/
        CommonCartridge12XMLFolder: C:/MMS-cache/CommonCartridge12xmls/
        CommonCartridge13XMLFolder: C:/MMS-cache/CommonCartridge13xmls/
        MDSExcelFolder: C:/MMS-cache/MDSExcels/
        EDExcelFolder: C:/MMS-cache/EDExcels/
        CorrelationsExcelFolder: C:/MMS-cache/CorrelationsExcels/
        ProgramStructureExcelFolder: C:/MMS-cache/ProgramStructureExcels/
        TCStndCorrelationsFolder: C:/MMS-cache/TCStandardCorrelationXmls/
        ExcludeAlchemyXmlToolType: '4, 7, 8, 9, 10, 11, 12, 13, 14, 15'
        ABStandardsXMLFolder: C:/MMS-cache/ABStandardXmls/
        HMSIStandardsXMLFolder: C:/MMS-cache/HMSIStandardXmls/
        svn.username: cust_dev_app
        svn.password: JDv9cpp        
    test:
        server:
            'contextPath': '/mms'
            session-timeout: 3600 # session timeout in seconds 
        grails.dbconsole.enabled: true
        dataSource:
            #dbCreate: update
            dbCreate: create-drop
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            pooled: true
            jmxExport: true
            driverClassName: org.h2.Driver
            username: sa
            password:
        CacheLocation: C:/MMS-cache/
        MDSXMLFolder: C:/MMS-cache/mdsxmls/
        PlannerXMLFolder: C:/MMS-cache/plannerxmls/
        AlchemyXMLFolder: C:/MMS-cache/alchemyxmls/
        MappingXMLFolder: C:/MMS-cache/MappingXml/
        CommonCartridge12XMLFolder: C:/MMS-cache/CommonCartridge12xmls/
        CommonCartridge13XMLFolder: C:/MMS-cache/CommonCartridge13xmls/
        CorrelationsExcelFolder: C:/MMS-cache/CorrelationsExcels/
        ProgramStructureExcelFolder: C:/MMS-cache/ProgramStructureExcels/
        MDSExcelFolder: C:/MMS-cache/MDSExcels/
        EDExcelFolder: C:/MMS-cache/EDExcels/
        TCStndCorrelationsFolder: C:/MMS-cache/TCStandardCorrelationXmls/
        ExcludeAlchemyXmlToolType: '4, 7, 8, 9, 10, 11, 12, 13, 14, 15'
        ABStandardsXMLFolder: C:/MMS-cache/ABStandardXmls/
        HMSIStandardsXMLFolder: C:/MMS-cache/HMSIStandardXmls/
        svn.username: cust_dev_app
        svn.password: JDv9cpp
    production:
        server:
            'contextPath': '/mms'
            session-timeout: 3600 # session timeout in seconds 
        dataSource:
            dbCreate: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            url: jdbc:mysql://10.94.42.35:3306/mms?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        CacheLocation: E:/MMS-cache/
        MDSXMLFolder: E:/MMS-cache/mdsxmls/
        PlannerXMLFolder: E:/MMS-cache/plannerxmls/
        AlchemyXMLFolder: E:/MMS-cache/alchemyxmls/
        MappingXMLFolder: E:/MMS-cache/MappingXml/
        CommonCartridge12XMLFolder: E:/MMS-cache/CommonCartridge12xmls/
        CommonCartridge13XMLFolder: E:/MMS-cache/CommonCartridge13xmls/
        MDSExcelFolder: E:/MMS-cache/MDSExcels/
        EDExcelFolder: E:/MMS-cache/EDExcels/
        CorrelationsExcelFolder: E:/MMS-cache/CorrelationsExcels/
        ProgramStructureExcelFolder: E:/MMS-cache/ProgramStructureExcels/
        TCStndCorrelationsFolder: E:/MMS-cache/TCStandardCorrelationXmls/
        ExcludeAlchemyXmlToolType: '4, 7, 8, 9, 10, 11, 12, 13, 14, 15'
        ABStandardsXMLFolder: E:/MMS-cache/ABStandardXmls/
        HMSIStandardsXMLFolder: E:/MMS-cache/HMSIStandardXmls/
        svn.username: cust_dev_app
        svn.password: JDv9cpp    
    nightly:
        server:
            'contextPath': '/mms'
            session-timeout: 3600 # session timeout in seconds 
        dataSource:
            dbCreate: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            url: jdbc:mysql://db:3306/mms?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        CacheLocation: E:/MMS-cache/
        MDSXMLFolder: E:/MMS-cache/mdsxmls/
        PlannerXMLFolder: E:/MMS-cache/plannerxmls/
        AlchemyXMLFolder: E:/MMS-cache/alchemyxmls/
        MappingXMLFolder: E:/MMS-cache/MappingXml/
        CommonCartridge12XMLFolder: E:/MMS-cache/CommonCartridge12xmls/
        CommonCartridge13XMLFolder: E:/MMS-cache/CommonCartridge13xmls/
        MDSExcelFolder: E:/MMS-cache/MDSExcels/
        EDExcelFolder: E:/MMS-cache/EDExcels/
        CorrelationsExcelFolder: E:/MMS-cache/CorrelationsExcels/
        ProgramStructureExcelFolder: E:/MMS-cache/ProgramStructureExcels/
        TCStndCorrelationsFolder: E:/MMS-cache/TCStandardCorrelationXmls/
        ExcludeAlchemyXmlToolType: '4, 7, 8, 9, 10, 11, 12, 13, 14, 15'
        ABStandardsXMLFolder: E:/MMS-cache/ABStandardXmls/
        HMSIStandardsXMLFolder: E:/MMS-cache/HMSIStandardXmls/
        svn.username: cust_dev_app
        svn.password: JDv9cpp          
---
---
grails:
    profile: angular
    codegen:
        defaultPackage: mms
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
---
grails: 
  plugin: 
    springsecurity: 
      authority: 
        className: hmh.mms.security.Role
      logout:
        postOnly: false
      controllerAnnotations: 
        staticRules: 
          - pattern: '/' 
            access: ['permitAll']
          - pattern: '/**' 
            access: ['permitAll']
          - pattern: '/**/css/**' 
            access: ['permitAll']
          - pattern: '/**/favicon.ico' 
            access: ['permitAll']
          - pattern: '/**/images/**' 
            access: ['permitAll']
          - pattern: '/**/js/**' 
            access: ['permitAll']
          - pattern: '/api/**' 
            access: ['permitAll']
          - pattern: '/assets/**' 
            access: ['permitAll']
          - pattern: '/error' 
            access: ['permitAll']
          - pattern: '/index' 
            access: ['permitAll']
          - pattern: '/index.gsp' 
            access: ['permitAll']
          - pattern: '/quartz/list' 
            access: ['ROLE_ADMIN']
          - pattern: '/shutdown' 
            access: ['permitAll']
      filterChain: 
        chainMap:
          - pattern: /assets/**         
            filters: none
          - pattern: /**/js/**                  
            filters: none
          - pattern: /**/css/**         
            filters: none
          - pattern: /**/images/** 
            filters: none
          - pattern: /**/favicon.ico       
            filters: none
          - pattern: /api/**
            filters: "JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter"
          - pattern: /**        
            filters: "JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter"            
      rest: 
        token: 
          storage: 
            jwt: 
              expiration: 518400 # 6 days
      userLookup: 
        authorityJoinClassName: hmh.mms.security.UserRole
        userDomainClassName: hmh.mms.security.User
        usernamePropertyName: email

